# **Titanic Survival Prediction Analysis**

**Name : Vinay Singh**

**Roll no : 2K24CSUN01139**

**Class : CSE-4**B

# **Load the Dataset**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Ensure 'titanic.csv' is in the same directory
df = pd.read_csv('titanic.csv')
print("Original Dataset:")
display(df.head())

Original Dataset:

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

# Data Cleaning

In [ ]:
columns_to_drop = ['PassengerId', 'Name', 'Ticket', 'Cabin']
df.drop(columns=columns_to_drop, inplace=True, errors='ignore')

print("Dataset after dropping columns:")
display(df.head())

Dataset after dropping columns:

,Survived,Pclass,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,male,22.0,1,0,7.2500
1,1,1,female,38.0,1,0,71.2833
2,1,3,female,26.0,0,0,7.9250
3,1,1,female,35.0,1,0,53.1000
4,0,3,male,35.0,0,0,8.0500

# **Handle Missing Values (Updated)**

In [ ]:
df['Age'] = df['Age'].fillna(df['Age'].median())
if 'Fare' in df.columns:
    df['Fare'] = df['Fare'].fillna(df['Fare'].median())

# Only attempt to fill 'Embarked' if the column exists
if 'Embarked' in df.columns:
    df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

df.dropna(inplace=True)

print("Missing values after imputation (should all be 0):")
print(df.isnull().sum())

Missing values after imputation (should all be 0):
Survived                   0
Pclass                     0
Sex                        0
Age                        0
Siblings/Spouses Aboard    0
Parents/Children Aboard    0
Fare                       0
dtype: int64

# Encode Categorical Variables

In [ ]:
if 'Sex' in df.columns:
    df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

if 'Embarked' in df.columns:
    df = pd.get_dummies(df, columns=['Embarked'], drop_first=False)

print("Dataset after encoding:")
display(df.head())

Dataset after encoding:

,Survived,Pclass,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,0,22.0,1,0,7.2500
1,1,1,1,38.0,1,0,71.2833
2,1,3,1,26.0,0,0,7.9250
3,1,1,1,35.0,1,0,53.1000
4,0,3,0,35.0,0,0,8.0500

# **Define Features and Target**

In [ ]:
X = df.drop('Survived', axis=1)
y = df['Survived']

# **Split the Dataset**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training features shape: {X_train.shape}")
print(f"Testing features shape: {X_test.shape}")

Training features shape: (709, 6)
Testing features shape: (178, 6)

# Feature Scaling

In [ ]:
scaler = StandardScaler()

X_train[['Age', 'Fare']] = scaler.fit_transform(X_train[['Age', 'Fare']])
X_test[['Age', 'Fare']] = scaler.transform(X_test[['Age', 'Fare']])

print("Scaled training features:")
display(X_train.head())

Scaled training features:

,Pclass,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
730,2,0,-0.449010,0,0,-0.388597
390,3,0,-0.094153,2,0,-0.484577
118,3,1,-1.939405,4,2,-0.042975
440,2,1,-0.094153,0,0,-0.388597
309,1,1,-0.803866,2,2,4.327664


# **Apply Logistic Regression**

In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)
print("Logistic Regression model trained successfully.")

Logistic Regression model trained successfully.

# **Make Predictions**

In [ ]:
y_pred = model.predict(X_test)
print("Predictions made on test data.")

Predictions made on test data.

# **Evaluating Model**

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("--- Model Evaluation Metrics ---")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}\n")

print("Confusion Matrix:")
print(conf_matrix)

--- Model Evaluation Metrics ---
Accuracy:  0.7472
Precision: 0.7115
Recall:    0.5522
F1-score:  0.6218

Confusion Matrix:
[[96 15]
 [30 37]]